export const TUTORIAL_INIT = 'TUTORIAL_INIT';
export const TUTORIAL_LOAD = 'TUTORIAL_LOAD';
export const TUTORIAL_BUILD = 'TUTORIAL_BUILD';

export const TUTORIAL_PAGE_ADD = 'TUTORIAL_PAGE_ADD';
export const TUTORIAL_TASK_ADD = 'TUTORIAL_TASK_ADD';
export const TUTORIAL_HINT_ADD = 'TUTORIAL_HINT_ADD';
export const TUTORIAL_ACTION_ADD = 'TUTORIAL_ACTION_ADD';
export const TUTORIAL_PUBLISH = 'TUTORIAL_PUBLISH';
