"use strict";
exports.TUTORIAL_INIT = 'TUTORIAL_INIT';
exports.TUTORIAL_LOAD = 'TUTORIAL_LOAD';
exports.TUTORIAL_BUILD = 'TUTORIAL_BUILD';
exports.TUTORIAL_PAGE_ADD = 'TUTORIAL_PAGE_ADD';
exports.TUTORIAL_TASK_ADD = 'TUTORIAL_TASK_ADD';
exports.TUTORIAL_HINT_ADD = 'TUTORIAL_HINT_ADD';
exports.TUTORIAL_ACTION_ADD = 'TUTORIAL_ACTION_ADD';
exports.TUTORIAL_PUBLISH = 'TUTORIAL_PUBLISH';
